version: '3.1'
services:
  book_postgres:
    image: postgres
    restart: always
    ports:
      - 25432:5432
    environment:
      POSTGRES_PASSWORD: test123
      POSTGRES_USER: writer
      POSTGRES_DB: books_library


  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181


  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  books_library:
      image: books-library:1.0.0
      ports:
        - 28877:8877
      environment:
        POSTGRES_HOST: book_postgres
        POSTGRES_PORT: 5432
        POSTGRES_USER: writer
        POSTGRES_PASSWORD: test123
        POSTGRES_DB: books_library
        KAFKA_HOST: kafka
        KAFKA_PORT: 9092

  book_downloader:
    image: book-downloader:1.0.0
    ports:
      - 26655:6655
    environment:
      POSTGRES_HOST: book_postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: writer
      POSTGRES_PASSWORD: test123
      POSTGRES_DB: books_library
      KAFKA_HOST: kafka
      KAFKA_PORT: 9092
